udp:
  listen: :4444
  maxPacketSize: 1024
  gateway: 192.168.1.55:4040

mqtt:
  broker: tcp://localhost:1883
  user:
  password:
  cleansession: true
  clientid: LoRaHomeServer

influxdb:
  addr: http://localhost:8086
  username:
  password:
  useragent: InfluxDBClient
  timeout: 0
  insecureskipverify: false
  defaultDatabase: test
